/**
 * Test Run Type Definitions
 * 
 * Centralized types for test run and test execution data.
 * Exports Zod schemas for runtime validation and inferred TypeScript types.
 * 
 * ARCHITECTURE:
 * - Discriminated unions for different test states
 * - Server and client can share these schemas via z.infer<>
 * - Runtime validation prevents type mismatches across network boundaries
 */

import { z } from 'zod'

/**
 * Test execution status
 */
export const TestStatusSchema = z.enum([
  'pending',
  'running',
  'passed',
  'failed',
  'skipped',
  'error',
])
export type TestStatus = z.infer<typeof TestStatusSchema>

/**
 * Individual test case
 */
export const TestCaseSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  file: z.string(),
  status: TestStatusSchema,
  duration: z.number().int().min(0),
  message: z.string().optional(),
  stack: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
})

export type TestCase = z.infer<typeof TestCaseSchema>

/**
 * Test suite (collection of test cases)
 */
export const TestSuiteSchema = z.object({
  id: z.string(),
  name: z.string(),
  file: z.string(),
  status: TestStatusSchema,
  tests: z.array(TestCaseSchema),
  totalTests: z.number().int(),
  passedTests: z.number().int(),
  failedTests: z.number().int(),
  skippedTests: z.number().int(),
  duration: z.number().int(),
  metadata: z.record(z.unknown()).optional(),
})

export type TestSuite = z.infer<typeof TestSuiteSchema>

/**
 * Code coverage data per file or overall
 */
export const CoverageSchema = z.object({
  file: z.string().optional().describe('File path; omit for overall coverage'),
  lines: z.number().min(0).max(100),
  branches: z.number().min(0).max(100).optional(),
  functions: z.number().min(0).max(100).optional(),
  statements: z.number().min(0).max(100).optional(),
})

export type Coverage = z.infer<typeof CoverageSchema>

/**
 * Test run status (top-level)
 */
export const TestRunStatusSchema = z.enum([
  'pending',      // Created but not started
  'running',      // Currently executing
  'completed',    // Finished successfully
  'failed',       // Finished with failures
  'cancelled',    // Cancelled before completion
  'error',        // Errored before tests could run
])
export type TestRunStatus = z.infer<typeof TestRunStatusSchema>

/**
 * Core Test Run object
 * Represents a single test execution across the codebase
 */
export const TestRunSchema = z.object({
  id: z.string().min(1),
  organizationId: z.string().uuid(),
  repositoryId: z.string(),
  
  // Metadata
  status: TestRunStatusSchema,
  title: z.string(),
  description: z.string().optional(),
  
  // Git context
  branch: z.string(),
  commitHash: z.string(),
  prNumber: z.number().int().optional(),
  
  // Execution
  startedAt: z.coerce.date().optional(),
  completedAt: z.coerce.date().optional(),
  durationMs: z.number().int().optional(),
  
  // Results
  suites: z.array(TestSuiteSchema).optional(),
  totalTests: z.number().int(),
  passedTests: z.number().int(),
  failedTests: z.number().int(),
  skippedTests: z.number().int(),
  
  // Coverage
  coverage: z.array(CoverageSchema).optional(),
  overallCoverage: CoverageSchema.optional(),
  coverageDelta: z.object({
    lines: z.number().optional(),
    branches: z.number().optional(),
    functions: z.number().optional(),
    statements: z.number().optional(),
  }).optional(),
  
  // Artifacts
  artifacts: z.array(z.object({
    name: z.string(),
    url: z.string().url(),
    type: z.enum(['test-report', 'coverage-report', 'log', 'html']),
  })).optional(),
  
  // Generation metadata
  generated: z.boolean().default(false).describe('Tests were generated by AI'),
  generatedTests: z.number().int().default(0),
  updatedTests: z.number().int().default(0),
  
  // Determinism & verification
  deterministic: z.boolean().optional().describe('Can be reproduced with same inputs'),
  signed: z.boolean().optional().describe('Cryptographically signed'),
  signatureHash: z.string().optional(),
  
  // Timestamps
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  
  // Additional metadata
  metadata: z.record(z.unknown()).optional(),
})

export type TestRun = z.infer<typeof TestRunSchema>

/**
 * Test Run with execution details
 * This is what gets returned from the API
 */
export const TestRunDetailSchema = TestRunSchema.extend({
  suites: z.array(TestSuiteSchema),
  coverage: z.array(CoverageSchema),
})

export type TestRunDetail = z.infer<typeof TestRunDetailSchema>

/**
 * Minimal test run summary
 * For list views and dashboards
 */
export const TestRunSummarySchema = TestRunSchema.pick({
  id: true,
  status: true,
  branch: true,
  commitHash: true,
  prNumber: true,
  totalTests: true,
  passedTests: true,
  failedTests: true,
  overallCoverage: true,
  startedAt: true,
  completedAt: true,
  durationMs: true,
  generated: true,
})

export type TestRunSummary = z.infer<typeof TestRunSummarySchema>

/**
 * Paginated test run list response
 */
export const TestRunListSchema = z.object({
  data: z.array(TestRunSummarySchema),
  pagination: z.object({
    total: z.number().int(),
    limit: z.number().int(),
    offset: z.number().int(),
    hasMore: z.boolean(),
  }),
})

export type TestRunList = z.infer<typeof TestRunListSchema>

/**
 * Single test run API response
 */
export const TestRunApiResponseSchema = z.object({
  data: TestRunDetailSchema,
})

/**
 * Type guards for test run states
 */
export function isTestRunCompleted(run: TestRun): run is TestRun & { completedAt: Date } {
  return run.status === 'completed' || run.status === 'failed' || run.status === 'cancelled'
}

export function isTestRunRunning(run: TestRun): boolean {
  return run.status === 'pending' || run.status === 'running'
}

export function isTestRunFailed(run: TestRun): boolean {
  return run.status === 'failed' || run.status === 'error'
}

export function isTestRunSuccessful(run: TestRun): boolean {
  return run.status === 'completed' && run.failedTests === 0
}

/**
 * Coverage calculation helpers
 */
export function calculateCoverageDelta(
  current: Coverage,
  baseline: Coverage
): number {
  return current.lines - baseline.lines
}

export function isCoverageImproved(delta: number): boolean {
  return delta > 0
}

export function isCoverageDegraded(delta: number): boolean {
  return delta < 0
}

/**
 * Test run state machine helpers
 */
export function canCancelTestRun(status: TestRunStatus): boolean {
  return status === 'pending' || status === 'running'
}

export function canRetryTestRun(status: TestRunStatus): boolean {
  return status === 'failed' || status === 'error'
}
